ARCHS = arm64 arm64e
TWEAK_NAME = Minimal
$(TWEAK_NAME)_FILES = Tweak.xm 
$(TWEAK_NAME)_CFLAGS = -fobjc-arc 
$(TWEAK_NAME)_FRAMEWORKS = UIKit

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk