TWEAK_NAME = Minimal

Minimal_FILES = Tweak.xm 
Minimal_CFLAGS = -fobjc-arc 
Minimal_FRAMEWORKS = UIKit
Minimal_EXTRA_FRAMEWORKS += Cephei 

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk