include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = MinimalPrefs

MinimalPrefs_FILES = MinimalRootListController.m POGSwitchWithInfoCell.m
MinimalPrefs_FRAMEWORKS = UIKit
MinimalPrefs_PRIVATE_FRAMEWORKS = Preferences
MinimalPrefs_INSTALL_PATH = /Library/PreferenceBundles
MinimalPrefs_CFLAGS = -fobjc-arc -Wdeprecated-declarations -Wno-deprecated-declarations

include $(THEOS_MAKE_PATH)/bundle.mk